# -*- coding: utf-8 -*-
"""cat_one_ho_encoder.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14NCWuPI2LWUtJSB5AZAwN9Bwx8mI549L
"""

import json
import pandas as pd
import numpy as np
from tqdm import tqdm
import os

from google.colab import drive
drive.mount('/content/drive')

cat_id_training_set= pd.read_csv('/content/drive/MyDrive/PhD/Polyvore_Outfit/disjoint/semantic_category_train_set.csv')

one_hot_cat_id_train_set=pd.DataFrame(np.zeros((len(cat_id_training_set),12)),dtype=int,columns=['Target','tops', 'jewellery', 'bottoms', 'all-body', 'sunglasses',
       'outerwear', 'hats', 'accessories', 'scarves', 'shoes', 'bags'])

cat_list=['tops', 'jewellery', 'bottoms', 'all-body', 'sunglasses',
       'outerwear', 'hats', 'accessories', 'scarves', 'shoes', 'bags']

for i in tqdm(range(len(cat_id_training_set))):
  for j in range(16):
    temp=cat_id_training_set.iloc[i,j+1]
    if temp in cat_list:
      one_hot_cat_id_train_set[temp][i] +=1
    elif temp == 0.0:
      continue

one_hot_cat_id_train_set['Target']=cat_id_training_set['Target']

one_hot_cat_id_train_set.to_csv('/content/drive/MyDrive/PhD/Polyvore_Outfit/disjoint/one_hot_seman_cat_train.csv',index=False)

